services:
  bedelia_frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - bedelia_backend
    environment:
      - REACT_APP_API_URL=http://localhost:3001/api/v1
      - NODE_ENV=production

  bedelia_backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./back/.env
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bedelia
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
